version: '3.4'

services:
  dev:
    image: nestjs_test
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - .:/usr/src/app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: